name: Build and Deploy to S3

run-name: Build and Deploy to S3 for ${{ github.event.repository.name }} (${{ inputs.environment || 'staging' }})
on:
  release:
    types: [created]

  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy to"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04-arm
    environment: ${{ inputs.environment || 'staging' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Upload jar to S3
        run: |
          JAR_FILE=$(find target -name "*.jar" | head -n 1)
          aws s3 cp "$JAR_FILE" s3://${{ env.S3_BUCKET_NAME }}/